spring:
  application:
    name: saas-foundry-api
  mvc:
    servlet:
      path: /api
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  datasource:
    url: ${POSTGRES_APP_DB_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # ddl-auto: update # For development. Use 'validate' or 'none' in production
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
  flyway:
    enabled: false

server:
  port: 6060

logging:
  file:
    name: logs/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

management:
  server:
    port: 6061
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: false
    rabbit:
      enabled: true
    db:
      enabled: true

keycloak:
  url: ${KEYCLOAK_URL}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  application-realm: ${KEYCLOAK_APPLICATION_REALM}

postgres:
  url: ${POSTGRES_DB_URL}
  default-db: ${POSTGRES_DEFAULT_DB}