-- Table: public.users

-- DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    email character varying(150) COLLATE pg_catalog."default",
    first_name character varying(50) COLLATE pg_catalog."default",
    is_keycloak_user_provisioned boolean,
    is_welcome_email_sent boolean,
    keycloak_user_provision_attempted_on timestamp(6) with time zone,
    last_name character varying(50) COLLATE pg_catalog."default",
    welcome_email_attempted_on timestamp(6) with time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to postgres;